name: BigBrother
version: 1.7.1
main: me.taylorkelly.bigbrother.BigBrother
commands:
  bb:
    description: All of the BigBrother commands
    usage: Command unrecognised by BigBrother. See documentation or use /bb help.