name: BigBrother
version: 1.5-SNAPSHOT
main: me.taylorkelly.bigbrother.BigBrother
commands:
  bb:
    description: All of the BigBrother commands
    usage: Command unrecognised, please read the documentation before using BigBrother.